# Generated by script/sim/write_jobs.R. Run with Rscript or source().
# Job 419: recessive_dominant_partial_recessive; K = 4; PVE = 0.3; replicates = 400.
.job_files <- vapply(sys.frames(), function(f) if (is.null(f$ofile)) "" else f$ofile, "")
.job_file <- if (any(nzchar(.job_files))) tail(.job_files[nzchar(.job_files)], 1L) else
  sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1L])
.job_file <- normalizePath(.job_file, winslash = "/", mustWork = TRUE)
project_dir <- normalizePath(file.path(dirname(.job_file), "../../.."), winslash = "/", mustWork = TRUE)
source(file.path(project_dir, "script/sim/run_job.R"), local = TRUE)
rm(.job_file, .job_files)

job <- data.frame(
  job_id = 419L,
  schema_version = 2L,
  name = "recessive_dominant_partial_recessive",
  K = 4L,
  L_add = 0L,
  L_rec = 2L,
  L_dom = 1L,
  L_prec = 1L,
  L_pdom = 0L,
  all_additive = FALSE,
  n = 500L,
  L = 10L,
  pve = 0.3,
  seed_base = 1000000L,
  reps_per_chunk = 400L,
  chunk = 1L,
  min_maf = 0.05,
  hwe_thresh = 1e-08,
  min_n_rec = 5L,
  slide_min_obs = 5L,
  delta_prec = -0.5,
  delta_pdom = 0.5,
  output_file = "simulation results/slide_v1/chunks/recessive_dominant_partial_recessive_add0_rec2_dom1_prec1_pdom0_n500_L10_pve0.3_seed1000000_reps400_chunk1.RData",
  row.names = 419L, stringsAsFactors = FALSE)

run_simulation_job(
  job_id = job$job_id, project_dir = project_dir, job = job,
  temp_dir = Sys.getenv("SUSIE_MIX_GENOTYPE_DIR", file.path(project_dir, "temp_plink")))
