#!/bin/bash
#SBATCH --job-name=cor_small_susie
#SBATCH --output=cor_small_susie.out
#SBATCH --error=cor_small_susie.err
#SBATCH --time=23:00:00
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=5000
#SBATCH --array=1-220

module load R/4.2.0
Rscript /project2/mstephens/wdenault/susie_mix/script/sim/jobs/sim_job_$SLURM_ARRAY_TASK_ID.R
