# generate_chunks.R
chunk_size <- 100

genes    <- readLines("/project2/mstephens/wdenault/susie_mix/data/genes_protein_coding.txt")
n_genes  <- length(genes)
n_chunks <- ceiling(n_genes / chunk_size)
cat(n_genes,"genes ->",n_chunks,"chunks of up to",chunk_size,"genes each\n")

index_dir   <- "/project2/mstephens/wdenault/susie_mix/data/temp_index"
script_dir  <- "/project2/mstephens/wdenault/susie_mix/script/scan_job"
results_dir <- "/project2/mstephens/wdenault/susie_mix/results"
workhorse   <- "/project2/mstephens/wdenault/susie_mix/script/scan_tissue_attempt/workhorse.R"

#dir.create(index_dir,  showWarnings = FALSE,recursive = TRUE)
#dir.create(script_dir, showWarnings = FALSE,recursive = TRUE)
#dir.create(results_dir,showWarnings = FALSE,recursive = TRUE)

for (i in seq_len(n_chunks)) {

  idx  <- ((i - 1) * chunk_size + 1):min(i * chunk_size,n_genes)
  gset <- genes[idx]
  tag  <- sprintf("%03d",i)

  gene_file <- file.path(index_dir,sprintf("chunk_%s_genes.txt",tag))
  writeLines(gset,gene_file)

  script_file <- file.path(script_dir,sprintf("run_chunk_%s.R",tag))

  # 6 real conversions below (the %%s inside the inner cat(sprintf(...))
  # are escaped and don't count) -> must pass exactly 6 arguments, in
  # this same order: tag, n genes, workhorse path, gene_file path,
  # results_dir, tag.
  script_txt <- sprintf('
# Auto-generated by generate_chunks.R -- chunk %s (%d genes)
source("%s", echo=FALSE)
genes <- readLines("%s")
for (target_gene in genes) {
  cat(sprintf("[%%s] starting %%s\\n", Sys.time(), target_gene))
  out <- tryCatch(
    run_susie_gene(target_gene= target_gene),
    error = function(e) list(gene = target_gene, error = conditionMessage(e))
  )
  saveRDS(out, file.path("%s", paste0(target_gene, ".rds")))
}
cat("Chunk %s done.\\n")
',tag,length(gset),workhorse,normalizePath(gene_file,mustWork = FALSE),
results_dir,tag)

  writeLines(script_txt,script_file)
}

cat("Wrote",n_chunks,"chunk gene lists to",index_dir,"\n")
cat("Wrote",n_chunks,"driver scripts to",script_dir,"\n")
cat("Set --array=1-",n_chunks," in submit_array.sh\n",sep = "")
