
# Auto-generated by generate_chunks.R -- chunk 056 (100 genes)
source("/project2/mstephens/wdenault/susie_mix/script/scan_tissue_attempt/workhorse.R", echo=FALSE)
genes <- readLines("/project2/mstephens/wdenault/susie_mix/data/temp_index/chunk_056_genes.txt")
for (target_gene in genes) {
  cat(sprintf("[%s] starting %s\n", Sys.time(), target_gene))
  out <- tryCatch(
    run_susie_gene(target_gene ),
    error = function(e) list(gene = target_gene, error = conditionMessage(e))
  )
  saveRDS(out, file.path("/project2/mstephens/wdenault/susie_mix/results", paste0(target_gene, ".rds")))
}
cat("Chunk 056 done.\n")

