#!/bin/bash
#SBATCH --job-name=test_mv_pois
#SBATCH --output=testmix_%A_%a.out
#SBATCH --error=testmix_%A_%a.err
#SBATCH --time=23:00:00
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=15000
#SBATCH --array=1-10

module load R/4.2.0

tag=$(printf "%03d" "$SLURM_ARRAY_TASK_ID")

Rscript /project2/mstephens/wdenault/susie_mix/script/scan_job/run_chunk_${tag}.R
