# Generate numbered R jobs and SLURM launchers; never fit or submit jobs here.
.job_sources <- vapply(sys.frames(), function(f) if (is.null(f$ofile)) "" else f$ofile, "")
.job_source <- if (any(nzchar(.job_sources))) tail(.job_sources[nzchar(.job_sources)], 1L) else
  sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1L])
.job_source <- normalizePath(.job_source, winslash = "/", mustWork = TRUE)
source(file.path(dirname(.job_source), "simulation_design.R"), local = TRUE)
sim_project_dir <- dirname(dirname(dirname(.job_source)))
rm(.job_source, .job_sources)

write_simulation_jobs <- function(project_dir = sim_project_dir,
                                  pve_values = c(.05, .10, .20, .30, .40),
                                  n = 500L, L = 10L, chunks_per_cell = 1L,
                                  reps_per_chunk = 400L, seed_base = 1000000L,
                                  array_batch_size = getOption("susie.sim.array_batch_size", 300L)) {
  stopifnot(length(pve_values) > 0L, !anyDuplicated(pve_values),
            all(pve_values > 0 & pve_values < 1), n >= 3, L >= 1,
            chunks_per_cell >= 1, reps_per_chunk >= 1,
            length(array_batch_size) == 1L, is.finite(array_batch_size),
            array_batch_size >= 1L, array_batch_size <= 400L,
            array_batch_size == floor(array_batch_size),
            all(c(n, L, chunks_per_cell, reps_per_chunk, seed_base) ==
                  floor(c(n, L, chunks_per_cell, reps_per_chunk, seed_base))))
  conditions <- sim_conditions()
  jobs <- list()
  for (i in seq_len(nrow(conditions))) {
    for (pve in pve_values) {
      for (chunk in seq_len(chunks_per_cell)) {
        condition <- conditions[i, , drop = FALSE]
        jobs[[length(jobs) + 1L]] <- data.frame(
          job_id = length(jobs) + 1L, schema_version = sim_schema_version,
          condition, n = n, L = L, pve = pve, seed_base = seed_base,
          reps_per_chunk = reps_per_chunk, chunk = chunk,
          min_maf = .05, hwe_thresh = 1e-8, min_n_rec = 5L, slide_min_obs = 5L,
          delta_prec = -.5, delta_pdom = .5,
          output_file = paste0("simulation results/slide_v1/chunks/",
            sim_checkpoint_name(condition, n, L, pve, seed_base, reps_per_chunk, chunk)))
      }
    }
  }
  manifest <- do.call(rbind, jobs)
  stopifnot(!anyDuplicated(manifest$output_file))
  job_dir <- file.path(project_dir, "script/sim/jobs_slide")
  dir.create(job_dir, recursive = TRUE, showWarnings = FALSE)
  write.csv(conditions, file.path(job_dir, "conditions.csv"), row.names = FALSE)
  write.csv(manifest, file.path(job_dir, "manifest.csv"), row.names = FALSE)

  # Read back once so embedded settings have the same types and row names as
  # the manifest runner. Each R job carries its own settings, including its
  # output filename; running it does not depend on a later-edited manifest.
  job_specs <- read.csv(file.path(job_dir, "manifest.csv"), stringsAsFactors = FALSE)
  for (i in seq_len(nrow(job_specs))) {
    row <- job_specs[i, , drop = FALSE]
    fields <- vapply(names(row), function(name) {
      paste0("  ", name, " = ", deparse(row[[name]]), ",")
    }, "")
    script <- c(
      "# Generated by script/sim/write_jobs.R. Run with Rscript or source().",
      paste0("# Job ", row$job_id, ": ", row$name, "; K = ", row$K,
             "; PVE = ", row$pve, "; replicates = ", row$reps_per_chunk, "."),
      ".job_files <- vapply(sys.frames(), function(f) if (is.null(f$ofile)) \"\" else f$ofile, \"\")",
      ".job_file <- if (any(nzchar(.job_files))) tail(.job_files[nzchar(.job_files)], 1L) else",
      "  sub(\"^--file=\", \"\", grep(\"^--file=\", commandArgs(FALSE), value = TRUE)[1L])",
      ".job_file <- normalizePath(.job_file, winslash = \"/\", mustWork = TRUE)",
      "project_dir <- normalizePath(file.path(dirname(.job_file), \"../../..\"), winslash = \"/\", mustWork = TRUE)",
      "source(file.path(project_dir, \"script/sim/run_job.R\"), local = TRUE)",
      "rm(.job_file, .job_files)",
      "", "job <- data.frame(", fields,
      paste0("  row.names = ", deparse(attr(row, "row.names")), ", stringsAsFactors = FALSE)"),
      "", "run_simulation_job(",
      "  job_id = job$job_id, project_dir = project_dir, job = job,",
      "  temp_dir = Sys.getenv(\"SUSIE_MIX_GENOTYPE_DIR\", file.path(project_dir, \"temp_plink\")))")
    writeLines(script, file.path(job_dir, paste0("sim_job_", row$job_id, ".R")),
               useBytes = TRUE)
  }

  offsets <- seq.int(0L, nrow(manifest) - 1L, by = array_batch_size)
  sizes <- pmin(array_batch_size, nrow(manifest) - offsets)
  batches <- data.frame(batch = seq_along(offsets), array_start = 0L,
                        array_end = sizes - 1L, offset = offsets,
                        first_job = offsets + 1L, last_job = offsets + sizes,
                        launcher = paste0("job/run_simulation_slide_batch_", seq_along(offsets)))
  write.csv(batches, file.path(job_dir, "submission_batches.csv"), row.names = FALSE)

  launcher_dir <- file.path(project_dir, "job")
  dir.create(launcher_dir, recursive = TRUE, showWarnings = FALSE)
  launcher_text <- function(size, offset) c(
    "#!/bin/bash",
    "# Generated by script/sim/write_jobs.R; runs numbered jobs_slide R files.",
    "#SBATCH --job-name=susie_slide_sim",
    "#SBATCH --output=susie_slide_sim_%A_%a.out",
    "#SBATCH --error=susie_slide_sim_%A_%a.err",
    "#SBATCH --time=23:00:00",
    "#SBATCH --partition=broadwl",
    "#SBATCH --nodes=1",
    "#SBATCH --ntasks=1",
    "#SBATCH --cpus-per-task=1",
    "#SBATCH --mem=20G",
    paste0("#SBATCH --array=0-", size - 1L),
    "", "set -euo pipefail",
    "# Wait for each batch to finish before submitting the next.",
    paste0("offset=\"${1:-", offset, "}\""),
    "task_id=\"${SLURM_ARRAY_TASK_ID:?Run this script as a SLURM array.}\"",
    "if [[ ! \"$offset\" =~ ^(0|[1-9][0-9]*)$ ]] ||",
    "   [[ ! \"$task_id\" =~ ^(0|[1-9][0-9]*)$ ]] || (( task_id >= 400 )); then",
    "  echo \"Expected a nonnegative offset and array indices between 0 and 399.\" >&2",
    "  exit 1", "fi",
    "job_id=$((offset + task_id + 1))",
    paste0("if (( job_id > ", nrow(manifest), " )); then"),
    paste0("  echo \"Simulation job $job_id is outside the generated range 1-", nrow(manifest), ".\" >&2"),
    "  exit 1", "fi",
    "project_dir=\"${SUSIE_MIX_PROJECT_DIR:-/project2/mstephens/wdenault/susie_mix}\"",
    "driver_script=\"$project_dir/script/sim/jobs_slide/sim_job_${job_id}.R\"",
    "if [[ ! -r \"$driver_script\" ]]; then",
    "  echo \"Missing simulation script: $driver_script. Run script/sim/write_jobs.R first.\" >&2",
    "  exit 1", "fi",
    "export OMP_NUM_THREADS=1",
    "export OPENBLAS_NUM_THREADS=1",
    "export MKL_NUM_THREADS=1",
    "module load R/4.2.0",
    "echo \"Starting simulation job $job_id at $(date)\"",
    "Rscript --vanilla \"$driver_script\"",
    "echo \"Finished simulation job $job_id at $(date)\"")
  # Binary connections preserve Unix line endings when generated on Windows
  # and then synced to RCC, where sbatch rejects CRLF shell scripts.
  write_launcher <- function(lines, path) {
    con <- file(path, open = "wb")
    on.exit(close(con))
    writeLines(lines, con, useBytes = TRUE)
  }
  for (i in seq_len(nrow(batches)))
    write_launcher(launcher_text(sizes[i], offsets[i]),
                   file.path(project_dir, batches$launcher[i]))
  write_launcher(launcher_text(sizes[1L], 0L),
                 file.path(launcher_dir, "run_simulation_slide"))

  # Remove only stale files owned by this generator when the batch size or
  # design changes. Never touch the legacy jobs or any saved results.
  old_scripts <- list.files(job_dir, "^sim_job_[0-9]+\\.R$", full.names = TRUE)
  keep_scripts <- file.path(job_dir, paste0("sim_job_", job_specs$job_id, ".R"))
  unlink(setdiff(old_scripts, keep_scripts))
  old_launchers <- list.files(launcher_dir, "^run_simulation_slide_batch_[0-9]+$", full.names = TRUE)
  unlink(setdiff(old_launchers, file.path(project_dir, batches$launcher)))

  cat("Generated", nrow(conditions), "configurations and", nrow(manifest), "R jobs (",
      sum(manifest$reps_per_chunk), "replicates).\n")
  cat("R scripts:", job_dir, "\n")
  cat("Submit from the project root. Existing queued/running jobs also use your QoS quota.\n")
  cat("Run all batches in sequence: sbatch job/launch_simulation_slide\n")
  cat("Or submit batches manually, ONE at a time, waiting for each to finish:\n")
  for (i in seq_len(nrow(batches))) {
    cat("  sbatch ", batches$launcher[i], "  # jobs ", batches$first_job[i], "-",
        batches$last_job[i], "\n", sep = "")
  }
  invisible(manifest)
}

# Sourcing is the usual preparation step. Tests/custom callers can opt out.
if (isTRUE(getOption("susie.sim.generate_jobs", TRUE))) write_simulation_jobs()
